services:
  - type: web
    name: pavakie-frontend
    env: static
    buildCommand: yarn build
    staticPublishPath: ./client/dist
    pullRequestPreviewEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 22.16.0

  - type: web
    name: pavakie-backend
    env: node
    buildCommand: cd server && yarn install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false

